In [84]:
# import required libraries
import pandas as pd
import yfinance as yf
import numpy as np
import math

In [85]:
# initializing 
ticker = 'TQQQ'
start_date = '2009-01-01'
end_date = '2019-01-01'

df = yf.download(ticker, start_date, end_date, threads= False)
df = df.reset_index()
df.head()

[*********************100%***********************]  1 of 1 completed

        Date      Open      High       Low     Close  Adj Close    Volume
0 2010-02-11  0.813750  0.869792  0.811146  0.865104   0.862942   1728000
1 2010-02-12  0.841563  0.876146  0.836667  0.868646   0.866475   4300800
2 2010-02-16  0.889063  0.904375  0.875104  0.902292   0.900037   4809600
3 2010-02-17  0.914375  0.917813  0.900625  0.917604   0.915311   9590400
4 2010-02-18  0.916667  0.940521  0.911146  0.935000   0.932663  19430400

In [86]:
# parameter setup (default values in the original indicator)
length = 20
mult = 2
length_KC = 20
mult_KC = 1.5

In [87]:
# calculate Bollinger Bands
# moving average
m_avg = df['Close'].rolling(window=length).mean()
# standard deviation
m_std = df['Close'].rolling(window=length).std(ddof=0)
# upper Bollinger Bands
df['upper_BB'] = m_avg + mult * m_std
# lower Bollinger Bands 
df['lower_BB'] = m_avg - mult * m_std

In [88]:
# calculate Keltner Channel
# first we need to calculate True Range
df['tr0'] = abs(df["High"] - df["Low"])
df['tr1'] = abs(df["High"] - df["Close"].shift())
df['tr2'] = abs(df["Low"] - df["Close"].shift())
df['tr'] = df[['tr0', 'tr1', 'tr2']].max(axis=1)
# moving average of the TR
range_ma = df['tr'].rolling(window=length_KC).mean()
# upper Keltner Channel
df['upper_KC'] = m_avg + range_ma * mult_KC
# lower Keltner Channel
df['lower_KC'] = m_avg - range_ma * mult_KC

In [89]:
# check for 'squeeze'
df['squeeze_on'] = (df['lower_BB'] > df['lower_KC']) & (df['upper_BB'] < df['upper_KC'])
df['squeeze_off'] = (df['lower_BB'] < df['lower_KC']) & (df['upper_BB'] > df['upper_KC'])

In [121]:
# calculate momentum value***
highest = df['High'].rolling(window = length_KC).max()
lowest = df['Low'].rolling(window = length_KC).min()
m1 = (highest + lowest) / 2
df['value'] = (df['Close'] - (m1 + m_avg)/2)
fit_y = np.array(range(0,length_KC))
df['value'] = df['value'].rolling(window = length_KC).apply(lambda x : np.polyfit(fit_y, x, 1)[0] * (length_KC-1) + np.polyfit(fit_y, x, 1)[1], raw=True)

In [122]:
# making sense of momentum value***
df['change'] = df['value'].diff()
df['rate of change'] = round(abs(df['change'] / df['value'].shift() * 100))
df

,Date,Open,High,Low,Close,Adj Close,Volume,upper_BB,lower_BB,tr0,...,lower_KC,squeeze_on,squeeze_off,value,change,rate of change,long_tqqq,exit_tqqq,long_sqqq,exit_sqqq
39,2010-04-09,1.200417,1.220938,1.191146,1.218021,1.214977,14524800,1.222061,1.082887,0.029792,...,1.099177,False,True,NaN,NaN,NaN,False,False,False,True
40,2010-04-12,1.222188,1.232292,1.214167,1.222917,1.219861,12201600,1.230071,1.087336,0.018125,...,1.105711,False,True,NaN,NaN,NaN,False,False,False,True
41,2010-04-13,1.218958,1.243333,1.207917,1.241354,1.238252,16809600,1.239127,1.093321,0.035416,...,1.112880,False,True,NaN,NaN,NaN,False,False,False,True
42,2010-04-14,1.259063,1.286146,1.256458,1.285104,1.281893,15273600,1.260005,1.089797,0.029688,...,1.120034,False,True,NaN,NaN,NaN,False,False,False,False
43,2010-04-15,1.283750,1.307083,1.282604,1.302292,1.299038,11443200,1.281696,1.086408,0.024479,...,1.129232,False,True,NaN,NaN,NaN,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,2018-12-24,16.000000,16.645000,15.160000,15.195000,15.163632,43900200,27.779867,16.110133,1.485001,...,19.188375,False,True,-4.296914,-1.068061,33.0,False,False,False,False
2233,2018-12-26,15.650000,17.969999,15.320000,17.930000,17.917162,94558800,27.787448,15.630552,2.650000,...,18.856375,False,True,-4.643566,-0.346652,8.0,False,False,False,True
2234,2018-12-27,17.299999,18.200001,16.059999,18.184999,18.171978,85458600,27.713691,15.234309,2.140001,...,18.544500,False,True,-4.874562,-0.230997,5.0,False,False,False,True
2235,2018-12-28,18.500000,19.055000,17.684999,18.110001,18.097033,76210600,27.303319,14.950181,1.370001,...,18.259125,False,True,-4.852144,0.022418,0.0,True,False,False,True
2236,2018-12-31,18.680000,18.840000,18.025000,18.520000,18.506739,54241600,26.842760,14.780241,0.815001,...,17.964875,False,True,-4.695135,0.157009,3.0,False,False,False,True

In [123]:
# entry point for long TQQQ:
# when value increases and is in negative range
df['long_tqqq'] = (df['change'] >= 0) & (df['change'].shift() <= 0) & (df['value'] < 0)

# exit point for TQQQ:
# when value decreases more than 50%
df['exit_tqqq'] = (df['rate of change'] >= 50)


# entry point for long SQQQ:
# when value decreases
df['long_sqqq'] = (df['rate of change'] >= 50) & (df['change'] > 0)

# exit point for SQQQ:
df['exit_sqqq'] = (df['rate of change'] < 10)

In [124]:
df = df.dropna()
df

,Date,Open,High,Low,Close,Adj Close,Volume,upper_BB,lower_BB,tr0,...,lower_KC,squeeze_on,squeeze_off,value,change,rate of change,long_tqqq,exit_tqqq,long_sqqq,exit_sqqq
78,2010-06-04,0.949167,0.986979,0.899375,0.912708,0.910427,61488000,1.154432,0.818026,0.087604,...,0.856292,False,True,-0.074326,-0.002012,3.0,False,False,False,True
79,2010-06-07,0.921563,0.931667,0.858333,0.859792,0.857643,42182400,1.158010,0.804469,0.073334,...,0.857224,False,True,-0.092955,-0.018629,25.0,False,False,False,False
80,2010-06-08,0.865938,0.871667,0.820938,0.855000,0.852863,66480000,1.144554,0.793154,0.050729,...,0.852011,False,True,-0.097342,-0.004387,5.0,False,False,False,True
81,2010-06-09,0.872292,0.896771,0.826563,0.836146,0.834056,57360000,1.129176,0.781949,0.070208,...,0.839492,False,True,-0.102283,-0.004942,5.0,False,False,False,True
82,2010-06-10,0.865313,0.907292,0.858229,0.905521,0.903258,38880000,1.089461,0.796080,0.049063,...,0.825997,False,True,-0.085256,0.017028,17.0,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,2018-12-24,16.000000,16.645000,15.160000,15.195000,15.163632,43900200,27.779867,16.110133,1.485001,...,19.188375,False,True,-4.296914,-1.068061,33.0,False,False,False,False
2233,2018-12-26,15.650000,17.969999,15.320000,17.930000,17.917162,94558800,27.787448,15.630552,2.650000,...,18.856375,False,True,-4.643566,-0.346652,8.0,False,False,False,True
2234,2018-12-27,17.299999,18.200001,16.059999,18.184999,18.171978,85458600,27.713691,15.234309,2.140001,...,18.544500,False,True,-4.874562,-0.230997,5.0,False,False,False,True
2235,2018-12-28,18.500000,19.055000,17.684999,18.110001,18.097033,76210600,27.303319,14.950181,1.370001,...,18.259125,False,True,-4.852144,0.022418,0.0,True,False,False,True
2236,2018-12-31,18.680000,18.840000,18.025000,18.520000,18.506739,54241600,26.842760,14.780241,0.815001,...,17.964875,False,True,-4.695135,0.157009,3.0,False,False,False,True

In [125]:
capital = 1000
start_long = capital/2
start_short = capital/2
long_fund = start_long
short_fund = start_short
Trades = []

In [126]:
for i in range(len(df)):
    if df['long_tqqq'].iloc[i] == True:
        trade = []
        for j in range(i + 1, len(df)):
            if df['exit_tqqq'].iloc[j] == True:
                gain_abs = df['Open'].iloc[j + 1] - df['Open'].iloc[i+1]
                gain_per = round(gain_abs / df['Open'].iloc[i+1] * 100,1)
                long_fund = round(long_fund * (100 + gain_per)/100,2)
#                 PnL.append(gain_abs)
#                 EnterDate.append(df['Date'].iloc[i+1])
#                 ExitDate.append(df['Date'].iloc[j+1])
                trade.append("Long")
                trade.append(gain_per)
                trade.append(long_fund)
                trade.append(df['Date'].iloc[i+1])
                trade.append(df['Date'].iloc[j+1])
                Trades.append(trade)
                
                # enter shorts immediately with the long funds
#                 trade = []
#                 for k in range(j + 1, len(df)):
#                     if df['close_sqqq'].iloc[k] == True:
#                         gain_abs =  df['Open'].iloc[j+1] - df['Open'].iloc[k + 1] #need to add SQQQ
#                         gain_per = round(gain_abs / df['Open'].iloc[i+1] * 100,1)
#                         long_fund = round(long_fund * (100 + gain_per)/100,2)
#                         trade.append("Short*")
#                         trade.append(gain_per)
#                         trade.append(long_fund)
#                         trade.append(df['Date'].iloc[j+1])
#                         trade.append(df['Date'].iloc[k+1])
#                         Trades.append(trade)
#                         break

                break
                
    if df['long_sqqq'].iloc[i] == True:
        trade = []
        for j in range(i + 1, len(df)):
                if df['exit_tqqq'].iloc[j] == True:
                    gain_abs =  df['Open'].iloc[i+1] - df['Open'].iloc[j + 1] #need to add SQQQ
                    gain_per = round(gain_abs / df['Open'].iloc[i+1] * 100,1)
                    short_fund = round(short_fund * (100 + gain_per)/100,2)
                    trade.append("Short")
                    trade.append(gain_per)
                    trade.append(short_fund)
                    trade.append(df['Date'].iloc[i+1])
                    trade.append(df['Date'].iloc[j+1])
                    Trades.append(trade)
                    break

In [127]:
for x in range(len(Trades)):
        print(Trades[x])

['Long', 13.6, 568.0, Timestamp('2010-06-11 00:00:00'), Timestamp('2010-06-16 00:00:00')]
['Short', -3.7, 481.5, Timestamp('2010-06-16 00:00:00'), Timestamp('2010-06-17 00:00:00')]
['Short', 0.0, 481.5, Timestamp('2010-06-17 00:00:00'), Timestamp('2010-06-18 00:00:00')]
['Short', 22.8, 591.28, Timestamp('2010-06-18 00:00:00'), Timestamp('2010-06-30 00:00:00')]
['Long', 3.7, 589.02, Timestamp('2010-07-13 00:00:00'), Timestamp('2010-07-21 00:00:00')]
['Short', 3.4, 611.38, Timestamp('2010-07-21 00:00:00'), Timestamp('2010-07-22 00:00:00')]
['Short', -1.3, 603.43, Timestamp('2010-07-22 00:00:00'), Timestamp('2010-07-23 00:00:00')]
['Short', -4.5, 576.28, Timestamp('2010-07-23 00:00:00'), Timestamp('2010-07-26 00:00:00')]
['Short', 10.8, 638.52, Timestamp('2010-07-26 00:00:00'), Timestamp('2010-08-16 00:00:00')]
['Long', 12.5, 662.65, Timestamp('2010-09-02 00:00:00'), Timestamp('2010-09-09 00:00:00')]
['Short', 1.1, 645.54, Timestamp('2010-09-09 00:00:00'), Timestamp('2010-09-10 00:00:00')]
['Short', -3.0, 626.17, Timestamp('2010-09-10 00:00:00'), Timestamp('2010-09-13 00:00:00')]
['Short', -1.3, 618.03, Timestamp('2010-09-13 00:00:00'), Timestamp('2010-09-14 00:00:00')]
['Short', -34.3, 406.05, Timestamp('2010-09-14 00:00:00'), Timestamp('2010-11-18 00:00:00')]
['Long', 3.5, 685.84, Timestamp('2010-12-02 00:00:00'), Timestamp('2010-12-06 00:00:00')]
['Short', -3.5, 391.84, Timestamp('2010-12-06 00:00:00'), Timestamp('2010-12-07 00:00:00')]
['Short', 2.5, 401.64, Timestamp('2010-12-07 00:00:00'), Timestamp('2010-12-08 00:00:00')]
['Short', -2.1, 393.21, Timestamp('2010-12-08 00:00:00'), Timestamp('2010-12-09 00:00:00')]
['Short', 0.9, 396.75, Timestamp('2010-12-09 00:00:00'), Timestamp('2010-12-10 00:00:00')]
['Short', -14.0, 341.2, Timestamp('2010-12-10 00:00:00'), Timestamp('2011-03-02 00:00:00')]
['Long', 9.4, 750.31, Timestamp('2011-03-22 00:00:00'), Timestamp('2011-03-31 00:00:00')]
['Short', -2.3, 333.35, Timestamp('2011-03-31 00:00:00'), Timestamp('2011-04-01 00:00:00')]
['Short', 0.4, 334.68, Timestamp('2011-04-01 00:00:00'), Timestamp('2011-04-04 00:00:00')]
['Short', 1.4, 339.37, Timestamp('2011-04-04 00:00:00'), Timestamp('2011-05-18 00:00:00')]
['Long', -8.9, 683.53, Timestamp('2011-06-01 00:00:00'), Timestamp('2011-06-30 00:00:00')]
['Long', 9.6, 749.15, Timestamp('2011-06-15 00:00:00'), Timestamp('2011-06-30 00:00:00')]
['Long', 12.3, 841.3, Timestamp('2011-06-21 00:00:00'), Timestamp('2011-06-30 00:00:00')]
['Short', -3.1, 328.85, Timestamp('2011-06-30 00:00:00'), Timestamp('2011-07-01 00:00:00')]
['Short', -4.6, 313.72, Timestamp('2011-07-01 00:00:00'), Timestamp('2011-07-05 00:00:00')]
['Short', -0.8, 311.21, Timestamp('2011-07-05 00:00:00'), Timestamp('2011-07-06 00:00:00')]
['Short', 4.2, 324.28, Timestamp('2011-07-06 00:00:00'), Timestamp('2011-08-02 00:00:00')]
['Long', 4.8, 881.68, Timestamp('2011-08-17 00:00:00'), Timestamp('2011-09-01 00:00:00')]
['Long', 17.7, 1037.74, Timestamp('2011-08-24 00:00:00'), Timestamp('2011-09-01 00:00:00')]
['Short', 8.9, 353.14, Timestamp('2011-09-01 00:00:00'), Timestamp('2011-09-02 00:00:00')]
['Short', 8.4, 382.8, Timestamp('2011-09-02 00:00:00'), Timestamp('2011-09-06 00:00:00')]
['Short', -13.9, 329.59, Timestamp('2011-09-06 00:00:00'), Timestamp('2011-09-08 00:00:00')]
['Short', 6.7, 351.67, Timestamp('2011-09-08 00:00:00'), Timestamp('2011-09-30 00:00:00')]
['Long', 19.8, 1243.21, Timestamp('2011-10-07 00:00:00'), Timestamp('2011-10-14 00:00:00')]
['Long', 11.4, 1384.94, Timestamp('2011-10-11 00:00:00'), Timestamp('2011-10-14 00:00:00')]
['Short', -0.2, 350.97, Timestamp('2011-10-14 00:00:00'), Timestamp('2011-10-17 00:00:00')]
['Short', 3.6, 363.6, Timestamp('2011-10-17 00:00:00'), Timestamp('2011-10-18 00:00:00')]
['Short', 0.8, 366.51, Timestamp('2011-10-18 00:00:00'), Timestamp('2011-11-10 00:00:00')]
['Long', -3.6, 1335.08, Timestamp('2011-11-16 00:00:00'), Timestamp('2011-11-17 00:00:00')]
['Long', 11.2, 1484.61, Timestamp('2011-11-29 00:00:00'), Timestamp('2011-12-08 00:00:00')]
['Short', 2.3, 374.94, Timestamp('2011-12-08 00:00:00'), Timestamp('2011-12-09 00:00:00')]
['Short', -0.6, 372.69, Timestamp('2011-12-09 00:00:00'), Timestamp('2011-12-12 00:00:00')]
['Short', -1.7, 366.35, Timestamp('2011-12-12 00:00:00'), Timestamp('2011-12-13 00:00:00')]
['Short', 3.5, 379.17, Timestamp('2011-12-13 00:00:00'), Timestamp('2011-12-27 00:00:00')]
['Long', 1.2, 1502.43, Timestamp('2012-01-04 00:00:00'), Timestamp('2012-01-05 00:00:00')]
['Short', -1.2, 374.62, Timestamp('2012-01-04 00:00:00'), Timestamp('2012-01-05 00:00:00')]
['Short', -3.3, 362.26, Timestamp('2012-01-05 00:00:00'), Timestamp('2012-01-06 00:00:00')]
['Short', -1.6, 356.46, Timestamp('2012-01-06 00:00:00'), Timestamp('2012-01-09 00:00:00')]
['Short', -50.6, 176.09, Timestamp('2012-01-09 00:00:00'), Timestamp('2012-04-12 00:00:00')]
['Long', -18.3, 1227.49, Timestamp('2012-04-26 00:00:00'), Timestamp('2012-06-13 00:00:00')]
['Long', 0.1, 1228.72, Timestamp('2012-05-25 00:00:00'), Timestamp('2012-06-13 00:00:00')]
['Short', 1.3, 178.38, Timestamp('2012-06-13 00:00:00'), Timestamp('2012-06-14 00:00:00')]
['Short', -1.9, 174.99, Timestamp('2012-06-14 00:00:00'), Timestamp('2012-06-15 00:00:00')]
['Short', -1.8, 171.84, Timestamp('2012-06-15 00:00:00'), Timestamp('2012-06-18 00:00:00')]
['Short', 1.7, 174.76, Timestamp('2012-06-18 00:00:00'), Timestamp('2012-07-13 00:00:00')]
['Long', 1.2, 1243.46, Timestamp('2012-07-19 00:00:00'), Timestamp('2012-07-20 00:00:00')]
['Short', -1.2, 172.66, Timestamp('2012-07-19 00:00:00'), Timestamp('2012-07-20 00:00:00')]
['Short', 11.7, 192.86, Timestamp('2012-07-20 00:00:00'), Timestamp('2012-07-25 00:00:00')]
['Long', -0.5, 1237.24, Timestamp('2012-07-30 00:00:00'), Timestamp('2012-07-31 00:00:00')]
['Short', -1.5, 189.97, Timestamp('2012-07-31 00:00:00'), Timestamp('2012-08-01 00:00:00')]
['Short', 5.3, 200.04, Timestamp('2012-08-01 00:00:00'), Timestamp('2012-08-02 00:00:00')]
['Short', -6.3, 187.44, Timestamp('2012-08-02 00:00:00'), Timestamp('2012-08-03 00:00:00')]
['Short', -2.4, 182.94, Timestamp('2012-08-03 00:00:00'), Timestamp('2012-08-06 00:00:00')]
['Short', -20.1, 146.17, Timestamp('2012-08-06 00:00:00'), Timestamp('2012-09-17 00:00:00')]
['Short', 0.9, 147.49, Timestamp('2012-09-17 00:00:00'), Timestamp('2012-09-18 00:00:00')]
['Short', 4.6, 154.27, Timestamp('2012-09-18 00:00:00'), Timestamp('2012-10-02 00:00:00')]
['Long', -6.6, 1155.58, Timestamp('2012-10-05 00:00:00'), Timestamp('2012-10-09 00:00:00')]
['Long', -14.2, 991.49, Timestamp('2012-10-17 00:00:00'), Timestamp('2012-11-28 00:00:00')]
['Long', -7.5, 917.13, Timestamp('2012-11-02 00:00:00'), Timestamp('2012-11-28 00:00:00')]
['Long', 7.9, 989.58, Timestamp('2012-11-19 00:00:00'), Timestamp('2012-11-28 00:00:00')]
['Short', -5.8, 145.32, Timestamp('2012-11-28 00:00:00'), Timestamp('2012-11-29 00:00:00')]
['Short', -0.2, 145.03, Timestamp('2012-11-29 00:00:00'), Timestamp('2012-11-30 00:00:00')]
['Short', -1.9, 142.27, Timestamp('2012-11-30 00:00:00'), Timestamp('2012-12-03 00:00:00')]
['Short', 6.6, 151.66, Timestamp('2012-12-03 00:00:00'), Timestamp('2012-12-27 00:00:00')]
['Long', -1.4, 975.73, Timestamp('2013-01-03 00:00:00'), Timestamp('2013-01-04 00:00:00')]
['Short', 1.4, 153.78, Timestamp('2013-01-03 00:00:00'), Timestamp('2013-01-04 00:00:00')]
['Short', 1.9, 156.7, Timestamp('2013-01-04 00:00:00'), Timestamp('2013-01-07 00:00:00')]
['Short', -0.9, 155.29, Timestamp('2013-01-07 00:00:00'), Timestamp('2013-01-08 00:00:00')]
['Short', -0.2, 154.98, Timestamp('2013-01-08 00:00:00'), Timestamp('2013-02-05 00:00:00')]
['Short', 0.4, 155.6, Timestamp('2013-02-11 00:00:00'), Timestamp('2013-02-12 00:00:00')]
['Short', -1.2, 153.73, Timestamp('2013-02-12 00:00:00'), Timestamp('2013-02-20 00:00:00')]
['Short', 6.1, 163.11, Timestamp('2013-02-20 00:00:00'), Timestamp('2013-02-22 00:00:00')]
['Long', 7.5, 1048.91, Timestamp('2013-02-28 00:00:00'), Timestamp('2013-03-06 00:00:00')]
['Long', 3.5, 1085.62, Timestamp('2013-03-05 00:00:00'), Timestamp('2013-03-06 00:00:00')]
['Short', 1.4, 165.39, Timestamp('2013-03-06 00:00:00'), Timestamp('2013-03-07 00:00:00')]
['Short', -1.5, 162.91, Timestamp('2013-03-07 00:00:00'), Timestamp('2013-03-08 00:00:00')]
['Short', 1.0, 164.54, Timestamp('2013-03-08 00:00:00'), Timestamp('2013-03-11 00:00:00')]
['Short', -0.3, 164.05, Timestamp('2013-03-11 00:00:00'), Timestamp('2013-03-12 00:00:00')]
['Short', 3.4, 169.63, Timestamp('2013-03-12 00:00:00'), Timestamp('2013-04-08 00:00:00')]
['Long', 4.0, 1129.04, Timestamp('2013-04-10 00:00:00'), Timestamp('2013-04-11 00:00:00')]
['Short', 0.1, 169.8, Timestamp('2013-04-11 00:00:00'), Timestamp('2013-04-12 00:00:00')]
['Short', 0.7, 170.99, Timestamp('2013-04-12 00:00:00'), Timestamp('2013-04-15 00:00:00')]
['Short', 10.0, 188.09, Timestamp('2013-04-15 00:00:00'), Timestamp('2013-04-19 00:00:00')]
['Long', 0.3, 1132.43, Timestamp('2013-04-23 00:00:00'), Timestamp('2013-04-24 00:00:00')]
['Short', -1.5, 185.27, Timestamp('2013-04-24 00:00:00'), Timestamp('2013-04-25 00:00:00')]
['Short', -0.0, 185.27, Timestamp('2013-04-25 00:00:00'), Timestamp('2013-04-26 00:00:00')]
['Short', -0.6, 184.16, Timestamp('2013-04-26 00:00:00'), Timestamp('2013-04-29 00:00:00')]
['Short', -2.2, 180.11, Timestamp('2013-04-29 00:00:00'), Timestamp('2013-04-30 00:00:00')]
['Short', -1.7, 177.05, Timestamp('2013-04-30 00:00:00'), Timestamp('2013-05-01 00:00:00')]
['Short', -8.5, 162.0, Timestamp('2013-05-01 00:00:00'), Timestamp('2013-06-05 00:00:00')]
['Long', 0.0, 1132.43, Timestamp('2013-06-18 00:00:00'), Timestamp('2013-07-09 00:00:00')]
['Long', 7.5, 1217.36, Timestamp('2013-06-27 00:00:00'), Timestamp('2013-07-09 00:00:00')]
['Short', -0.1, 161.84, Timestamp('2013-07-09 00:00:00'), Timestamp('2013-07-10 00:00:00')]
['Short', -5.3, 153.26, Timestamp('2013-07-10 00:00:00'), Timestamp('2013-07-11 00:00:00')]
['Short', -3.0, 148.66, Timestamp('2013-07-11 00:00:00'), Timestamp('2013-07-12 00:00:00')]
['Short', -1.3, 146.73, Timestamp('2013-07-12 00:00:00'), Timestamp('2013-08-21 00:00:00')]
['Long', -6.4, 1139.45, Timestamp('2013-08-26 00:00:00'), Timestamp('2013-08-28 00:00:00')]
['Long', 4.8, 1194.14, Timestamp('2013-08-30 00:00:00'), Timestamp('2013-09-09 00:00:00')]
['Long', 4.3, 1245.49, Timestamp('2013-09-04 00:00:00'), Timestamp('2013-09-09 00:00:00')]
['Short', -4.1, 140.71, Timestamp('2013-09-09 00:00:00'), Timestamp('2013-09-10 00:00:00')]
['Short', 2.2, 143.81, Timestamp('2013-09-10 00:00:00'), Timestamp('2013-09-11 00:00:00')]
['Short', -1.5, 141.65, Timestamp('2013-09-11 00:00:00'), Timestamp('2013-09-12 00:00:00')]
['Short', 2.1, 144.62, Timestamp('2013-09-12 00:00:00'), Timestamp('2013-10-09 00:00:00')]
['Long', 1.0, 1257.94, Timestamp('2013-10-15 00:00:00'), Timestamp('2013-10-17 00:00:00')]
['Short', -6.0, 135.94, Timestamp('2013-10-17 00:00:00'), Timestamp('2013-10-18 00:00:00')]
['Short', -2.7, 132.27, Timestamp('2013-10-18 00:00:00'), Timestamp('2013-10-21 00:00:00')]
['Short', -2.2, 129.36, Timestamp('2013-10-21 00:00:00'), Timestamp('2013-11-21 00:00:00')]
['Short', 0.1, 129.49, Timestamp('2013-11-25 00:00:00'), Timestamp('2013-11-26 00:00:00')]
['Short', -2.1, 126.77, Timestamp('2013-11-26 00:00:00'), Timestamp('2013-11-27 00:00:00')]
['Short', -2.6, 123.47, Timestamp('2013-11-27 00:00:00'), Timestamp('2013-11-29 00:00:00')]
['Short', 0.4, 123.96, Timestamp('2013-11-29 00:00:00'), Timestamp('2014-01-28 00:00:00')]
['Long', 3.5, 1301.97, Timestamp('2014-02-10 00:00:00'), Timestamp('2014-02-13 00:00:00')]
['Short', -4.7, 118.13, Timestamp('2014-02-13 00:00:00'), Timestamp('2014-02-14 00:00:00')]
['Short', -0.9, 117.07, Timestamp('2014-02-14 00:00:00'), Timestamp('2014-02-18 00:00:00')]
['Short', -0.5, 116.48, Timestamp('2014-02-18 00:00:00'), Timestamp('2014-02-19 00:00:00')]
['Short', 2.0, 118.81, Timestamp('2014-02-19 00:00:00'), Timestamp('2014-03-17 00:00:00')]
['Long', -7.8, 1200.42, Timestamp('2014-04-02 00:00:00'), Timestamp('2014-05-01 00:00:00')]
['Long', -1.9, 1177.61, Timestamp('2014-04-10 00:00:00'), Timestamp('2014-05-01 00:00:00')]
['Long', 5.9, 1247.09, Timestamp('2014-04-16 00:00:00'), Timestamp('2014-05-01 00:00:00')]
['Short', -1.3, 117.27, Timestamp('2014-05-01 00:00:00'), Timestamp('2014-05-02 00:00:00')]
['Short', 3.2, 121.02, Timestamp('2014-05-02 00:00:00'), Timestamp('2014-05-05 00:00:00')]
['Short', -25.6, 90.04, Timestamp('2014-05-05 00:00:00'), Timestamp('2014-08-06 00:00:00')]
['Long', 5.8, 1319.42, Timestamp('2014-08-14 00:00:00'), Timestamp('2014-08-19 00:00:00')]
['Short', -0.7, 89.41, Timestamp('2014-08-19 00:00:00'), Timestamp('2014-08-20 00:00:00')]
['Short', -0.5, 88.96, Timestamp('2014-08-20 00:00:00'), Timestamp('2014-08-21 00:00:00')]
['Short', -0.5, 88.52, Timestamp('2014-08-21 00:00:00'), Timestamp('2014-08-22 00:00:00')]
['Short', -2.5, 86.31, Timestamp('2014-08-22 00:00:00'), Timestamp('2014-09-18 00:00:00')]
['Long', -4.4, 1261.37, Timestamp('2014-09-25 00:00:00'), Timestamp('2014-09-26 00:00:00')]
['Long', -1.6, 1241.19, Timestamp('2014-10-01 00:00:00'), Timestamp('2014-10-27 00:00:00')]
['Long', -1.1, 1227.54, Timestamp('2014-10-06 00:00:00'), Timestamp('2014-10-27 00:00:00')]
['Long', -0.6, 1220.17, Timestamp('2014-10-09 00:00:00'), Timestamp('2014-10-27 00:00:00')]
['Long', 9.0, 1329.99, Timestamp('2014-10-21 00:00:00'), Timestamp('2014-10-27 00:00:00')]
['Short', -2.1, 84.5, Timestamp('2014-10-27 00:00:00'), Timestamp('2014-10-28 00:00:00')]
['Short', -2.1, 82.73, Timestamp('2014-10-28 00:00:00'), Timestamp('2014-10-29 00:00:00')]
['Short', 1.5, 83.97, Timestamp('2014-10-29 00:00:00'), Timestamp('2014-10-30 00:00:00')]
['Short', -10.2, 75.41, Timestamp('2014-10-30 00:00:00'), Timestamp('2014-12-12 00:00:00')]
['Long', 2.0, 1356.59, Timestamp('2014-12-19 00:00:00'), Timestamp('2014-12-30 00:00:00')]
['Short', 0.7, 75.94, Timestamp('2014-12-30 00:00:00'), Timestamp('2014-12-31 00:00:00')]
['Short', 10.6, 83.99, Timestamp('2014-12-31 00:00:00'), Timestamp('2015-01-07 00:00:00')]
['Short', 3.3, 86.76, Timestamp('2015-01-09 00:00:00'), Timestamp('2015-01-13 00:00:00')]
['Long', -2.6, 1321.32, Timestamp('2015-01-22 00:00:00'), Timestamp('2015-01-30 00:00:00')]
['Short', -1.5, 85.46, Timestamp('2015-01-30 00:00:00'), Timestamp('2015-02-03 00:00:00')]
['Short', -0.6, 84.95, Timestamp('2015-02-03 00:00:00'), Timestamp('2015-02-04 00:00:00')]
['Short', -4.1, 81.47, Timestamp('2015-02-04 00:00:00'), Timestamp('2015-02-06 00:00:00')]
['Short', 3.4, 84.24, Timestamp('2015-02-06 00:00:00'), Timestamp('2015-02-09 00:00:00')]
['Short', -6.3, 78.93, Timestamp('2015-02-09 00:00:00'), Timestamp('2015-03-12 00:00:00')]
['Long', -3.6, 1273.75, Timestamp('2015-03-20 00:00:00'), Timestamp('2015-04-16 00:00:00')]
['Long', 3.0, 1311.96, Timestamp('2015-03-31 00:00:00'), Timestamp('2015-04-16 00:00:00')]
['Long', 9.0, 1430.04, Timestamp('2015-04-06 00:00:00'), Timestamp('2015-04-16 00:00:00')]
['Short', 2.5, 80.9, Timestamp('2015-04-16 00:00:00'), Timestamp('2015-04-17 00:00:00')]
['Short', -4.3, 77.42, Timestamp('2015-04-17 00:00:00'), Timestamp('2015-04-21 00:00:00')]
['Short', -0.3, 77.19, Timestamp('2015-04-21 00:00:00'), Timestamp('2015-04-22 00:00:00')]
['Short', 0.1, 77.27, Timestamp('2015-04-22 00:00:00'), Timestamp('2015-04-23 00:00:00')]
['Short', -0.0, 77.27, Timestamp('2015-04-23 00:00:00'), Timestamp('2015-05-08 00:00:00')]
['Long', -0.2, 1427.18, Timestamp('2015-05-15 00:00:00'), Timestamp('2015-05-21 00:00:00')]
['Long', -1.0, 1412.91, Timestamp('2015-05-19 00:00:00'), Timestamp('2015-05-21 00:00:00')]
['Short', -1.7, 75.96, Timestamp('2015-05-21 00:00:00'), Timestamp('2015-05-22 00:00:00')]
['Short', 0.6, 76.42, Timestamp('2015-05-22 00:00:00'), Timestamp('2015-05-26 00:00:00')]
['Short', -1.3, 75.43, Timestamp('2015-05-26 00:00:00'), Timestamp('2015-05-28 00:00:00')]
['Short', 6.4, 80.26, Timestamp('2015-05-28 00:00:00'), Timestamp('2015-06-10 00:00:00')]
['Long', 0.9, 1425.63, Timestamp('2015-06-19 00:00:00'), Timestamp('2015-06-23 00:00:00')]
['Short', 0.5, 80.66, Timestamp('2015-06-23 00:00:00'), Timestamp('2015-06-24 00:00:00')]
['Short', 0.1, 80.74, Timestamp('2015-06-24 00:00:00'), Timestamp('2015-06-25 00:00:00')]
['Short', 1.8, 82.19, Timestamp('2015-06-25 00:00:00'), Timestamp('2015-06-26 00:00:00')]
['Short', 6.8, 87.78, Timestamp('2015-06-26 00:00:00'), Timestamp('2015-06-30 00:00:00')]
['Long', 8.7, 1549.66, Timestamp('2015-07-14 00:00:00'), Timestamp('2015-07-17 00:00:00')]
['Short', -2.7, 85.41, Timestamp('2015-07-17 00:00:00'), Timestamp('2015-07-20 00:00:00')]
['Short', -0.4, 85.07, Timestamp('2015-07-20 00:00:00'), Timestamp('2015-07-21 00:00:00')]
['Short', 4.9, 89.24, Timestamp('2015-07-21 00:00:00'), Timestamp('2015-07-22 00:00:00')]
['Short', 3.3, 92.18, Timestamp('2015-07-22 00:00:00'), Timestamp('2015-08-10 00:00:00')]
['Long', -36.3, 987.13, Timestamp('2015-08-18 00:00:00'), Timestamp('2015-08-24 00:00:00')]
['Long', 0.2, 989.1, Timestamp('2015-08-28 00:00:00'), Timestamp('2015-09-15 00:00:00')]
['Long', 3.0, 1018.77, Timestamp('2015-09-03 00:00:00'), Timestamp('2015-09-15 00:00:00')]
['Short', -2.9, 89.51, Timestamp('2015-09-15 00:00:00'), Timestamp('2015-09-16 00:00:00')]
['Short', -1.4, 88.26, Timestamp('2015-09-16 00:00:00'), Timestamp('2015-09-17 00:00:00')]
['Short', 4.2, 91.97, Timestamp('2015-09-17 00:00:00'), Timestamp('2015-09-18 00:00:00')]
['Short', 12.4, 103.37, Timestamp('2015-09-18 00:00:00'), Timestamp('2015-09-30 00:00:00')]
['Long', 1.4, 1033.03, Timestamp('2015-10-07 00:00:00'), Timestamp('2015-10-13 00:00:00')]
['Short', 0.2, 103.58, Timestamp('2015-10-13 00:00:00'), Timestamp('2015-10-14 00:00:00')]
['Short', -0.6, 102.96, Timestamp('2015-10-14 00:00:00'), Timestamp('2015-10-15 00:00:00')]
['Short', -4.5, 98.33, Timestamp('2015-10-15 00:00:00'), Timestamp('2015-10-16 00:00:00')]
['Short', -0.1, 98.23, Timestamp('2015-10-16 00:00:00'), Timestamp('2015-10-19 00:00:00')]
['Short', -9.7, 88.7, Timestamp('2015-10-19 00:00:00'), Timestamp('2015-11-17 00:00:00')]
['Long', 1.8, 1051.62, Timestamp('2015-11-23 00:00:00'), Timestamp('2015-12-02 00:00:00')]
['Short', 1.2, 89.76, Timestamp('2015-12-02 00:00:00'), Timestamp('2015-12-03 00:00:00')]
['Short', -0.9, 88.95, Timestamp('2015-12-03 00:00:00'), Timestamp('2015-12-07 00:00:00')]
['Short', 4.6, 93.04, Timestamp('2015-12-07 00:00:00'), Timestamp('2015-12-08 00:00:00')]
['Short', 2.5, 95.37, Timestamp('2015-12-08 00:00:00'), Timestamp('2015-12-15 00:00:00')]
['Long', -6.9, 979.06, Timestamp('2015-12-24 00:00:00'), Timestamp('2016-01-05 00:00:00')]
['Long', -4.0, 939.9, Timestamp('2016-01-25 00:00:00'), Timestamp('2016-02-23 00:00:00')]
['Long', 23.8, 1163.6, Timestamp('2016-02-11 00:00:00'), Timestamp('2016-02-23 00:00:00')]
['Long', 9.4, 1272.98, Timestamp('2016-02-16 00:00:00'), Timestamp('2016-02-23 00:00:00')]
['Short', 6.6, 101.66, Timestamp('2016-02-23 00:00:00'), Timestamp('2016-02-24 00:00:00')]
['Short', -7.3, 94.24, Timestamp('2016-02-24 00:00:00'), Timestamp('2016-02-25 00:00:00')]
['Short', -19.4, 75.96, Timestamp('2016-02-25 00:00:00'), Timestamp('2016-04-26 00:00:00')]
['Long', 4.5, 1330.26, Timestamp('2016-05-11 00:00:00'), Timestamp('2016-05-25 00:00:00')]
['Short', -1.3, 74.97, Timestamp('2016-05-25 00:00:00'), Timestamp('2016-05-26 00:00:00')]
['Short', -0.7, 74.45, Timestamp('2016-05-26 00:00:00'), Timestamp('2016-05-27 00:00:00')]
['Short', -1.9, 73.04, Timestamp('2016-05-27 00:00:00'), Timestamp('2016-05-31 00:00:00')]
['Short', 6.3, 77.64, Timestamp('2016-05-31 00:00:00'), Timestamp('2016-06-20 00:00:00')]
['Long', 7.6, 1431.36, Timestamp('2016-06-30 00:00:00'), Timestamp('2016-07-08 00:00:00')]
['Short', -4.3, 74.3, Timestamp('2016-07-08 00:00:00'), Timestamp('2016-07-11 00:00:00')]
['Short', -2.4, 72.52, Timestamp('2016-07-11 00:00:00'), Timestamp('2016-07-12 00:00:00')]
['Short', -0.5, 72.16, Timestamp('2016-07-12 00:00:00'), Timestamp('2016-07-13 00:00:00')]
['Short', -12.4, 63.21, Timestamp('2016-07-13 00:00:00'), Timestamp('2016-08-31 00:00:00')]

In [128]:
print("ticker: ", ticker)
print("start date: ", Trades[0][3])
print("end date: ", Trades[len(Trades)-1][3])
print("total starting capital: ", capital)
print("long fund: ", start_long)
print("short fund: ", start_short)
total_returns = round(long_fund + short_fund,2)
print("final capital: ", total_returns)
print("final long: ", long_fund)
print("final short: ", short_fund)
pnl = round(long_fund + short_fund - capital,2)
print("pnl: ", pnl)
print("pnl%: ", round((pnl/capital * 100),2))

years = (Trades[len(Trades)-1][3] - Trades[0][3]).days/365
annualized = round((pow((total_returns / capital),1/years)-1)*100,2)
print("annualized%: ", annualized)

ticker:  TQQQ
start date:  2010-06-11 00:00:00
end date:  2018-12-07 00:00:00
total starting capital:  1000
long fund:  500.0
short fund:  500.0
final capital:  2222.24
final long:  2168.84
final short:  53.4
pnl:  1222.24
pnl%:  122.22
annualized%:  9.85

In [129]:
win_counts = 0
lose_counts = 0

for x in range(len(Trades)):
    if(Trades[x][1] > 0):
        win_counts += 1
    else:
        lose_counts += 1
        
print("win_counts: ", win_counts, "lose_counts: ", lose_counts)

win_counts:  141 lose_counts:  149

In [113]:
short_win_counts = 0
short_lose_counts = 0

for x in range(len(Trades)):
    if (Trades[x][0] == 'Short'):
        if(Trades[x][1] > 0):
            short_win_counts += 1
        else:
            short_lose_counts += 1
        
print("short_win_counts: ", short_win_counts, "short_lose_counts: ", short_lose_counts)

short_win_counts:  164 short_lose_counts:  235